add parameter to set excution time limit per worker
fd0/machma pull request #6
Opened 2017-04-12 08:09 UTC by jkahrs

This pr adds a --timeout option to specify a maximum runtime for machma worker processes.
The value for --timeout is set according to https://golang.org/pkg/time/#ParseDuration

2017-04-12 08:15 UTC, fd0 requested changes

2017-04-12 08:15 UTC, fd0 commented on main.go
> +	workerTimeout    string
Use `time.Duration` instead of `string` here

2017-04-12 08:15 UTC, fd0 commented on main.go
> +	pflag.StringVar(&opts.workerTimeout, "timeout", "0s", "set maximum runtime per queued job (0s == no limit)")
Then you can use `pflag.DurationVar` here, so parsing is handled by pflag. https://godoc.org/github.com/spf13/pflag#DurationVar

2017-04-12 08:15 UTC, fd0 commented on worker.go
> +	err = cmd.Start()
For Go >= 1.7 this is much nicer:
```go
ctx, cancel := context.WithDeadline(context.Background(), opts.WorkerTimeout)
defer cancel()

cmd := exec.CommandContext(ctx, c.Cmd, c.Args...)
```

https://godoc.org/os/exec#CommandContext

2017-04-12 08:15 UTC, fd0 commented on worker.go
>  	defer wg.Wait()
In order for this to work we need to remove the `defer` here.

2017-04-12 08:16 UTC, fd0 commented
Great idea btw, love it!

2017-04-12 10:58 UTC, fd0 commented
Let me know if you need any  further help. We can safely assume that users have Go >= 1.7.

2017-04-12 13:20 UTC, jkahrs commented on worker.go
I should make sure that those finis somehow

2017-04-12 17:59 UTC, fd0 approved these changes

2017-04-12 18:15 UTC, merged

2017-04-28 04:48 UTC, johnny2k commented
This is an awesome addition. Nice work! I'm doing a demo next week using machma so this will help it go very smooth.